### ISSUE TITLE
Weird Bug

### ISSUE THREAD

**Issue by sheesh-mate** [aiko-chan-ai/DiscordBotClient#10]
Channels don’t load in some servers even tho the bot has admin. Even its permissions won’t clearly appear in half of the servers. I’ve confirmed bot has admin in the said servers but the bot client will only load publicly viewable channels and not all (which it should using its admin perms)

**Comment by aiko-chan-ai** [comment]
can you give me more information or video it?

**Comment by sheesh-mate** [comment]
So, in a server, bot has admin permissions and should see all channels but when I open a server it only shows the default available channels, and when I send a message in any channel then bot loads the channels as it should (because of admin perms)

**Comment by aiko-chan-ai** [comment]
confirmed
