### ISSUE TITLE
Copying a Webhook URL copies a localhost link

### ISSUE THREAD

**Issue by VillainsRule** [aiko-chan-ai/DiscordBotClient#108]
Normal webhook:
https://discord.com/api/webhooks/CREATOR_ID/HOOK_ID

Bot client webhook:
https://localhost:2023/d/api/webhooks/CREATOR_ID/HOOK_ID

**Comment by aiko-chan-ai** [comment]
https://github.com/aiko-chan-ai/DiscordBotClient/commit/694c65cb74d4abe0f987a67686a496c0a4fce63c

**Comment by aiko-chan-ai** [comment]
v3.2.0 🎉
