### ISSUE TITLE
discord bot with nitro

### ISSUE THREAD

**Issue by heegvn** [aiko-chan-ai/DiscordBotClient#109]
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/114314659/ed1e7aab-7701-4acd-b8c4-b8b08266b478)

**Comment by aiko-chan-ai** [comment]
https://github.com/aiko-chan-ai/DiscordBotClient/blob/electron-v3/AppAssets/Util.js#L17
I use an animated avatar to know if the user has nitro or not, and the current bot user also has an animated avatar. I will fix this soon

**Comment by heegvn** [comment]
okay ><

**Comment by aiko-chan-ai** [comment]
v3.2.0 🎉
