### ISSUE TITLE
Infinite loading

### ISSUE THREAD

**Issue by GardoTL** [aiko-chan-ai/DiscordBotClient#11]
Infinite loading with a bot token on more than 1000 servers.

**Comment by aiko-chan-ai** [comment]
> 

discord client is not designed for too many servers, but with 600 servers it works :c

**Comment by GardoTL** [comment]
It is impossible to cut the servers in increments of 500?

**Comment by aiko-chan-ai** [comment]
idk ... try it and see (fork main branch and edit)

**Comment by aiko-chan-ai** [comment]
@GardoTL maybe the module is not loaded... you can use `ctrl + R` to restart the application
