### ISSUE TITLE
nothing happens when i open the app?

### ISSUE THREAD

**Issue by ethavn** [aiko-chan-ai/DiscordBotClient#110]
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/155512555/26fb38a7-9bd8-4e9d-b701-c8af6c1a70c5)
this is all i see

**Comment by aiko-chan-ai** [comment]
that's not this client, it should look like this
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/ed7b9216-da69-40a9-8bc5-028961743a7f)
