### ISSUE TITLE
DiscardVirtualMemory in DiscordBotClient v3.1.3 Windows 7 x64

### ISSUE THREAD

**Issue by CasherGames** [aiko-chan-ai/DiscordBotClient#111]
o have problem in discordbotclient version 3.1.3

![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/86890809/4b26e333-b55a-4adc-9d45-bf97bd3b2b25)

please help me!

**Comment by aiko-chan-ai** [comment]
Electron v28 not support

**Comment by aiko-chan-ai** [comment]
Using v2

**Comment by aiko-chan-ai** [comment]
or I will downgrade the electron later

**Comment by CasherGames** [comment]
yes please

**Comment by CasherGames** [comment]
can run discord with build Stable 263796 in electron v2 ?

**Comment by aiko-chan-ai** [comment]
No :))

**Comment by CasherGames** [comment]
ok :))

**Comment by CasherGames** [comment]
hey

**Comment by aiko-chan-ai** [comment]
i think you can build from source

**Comment by CasherGames** [comment]
how ?

**Comment by CasherGames** [comment]
i trying change "resources" folder and its running
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/86890809/22e3a995-52da-4e88-808b-561c0122d682)
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/86890809/29459f05-3a7e-42b3-bb84-c8ad09a5e90b)
