### ISSUE TITLE
[FEATURE REQUEST] Add more options to /embed

### ISSUE THREAD

**Issue by mrkingtj** [aiko-chan-ai/DiscordBotClient#112]
/embed only supports a title, colour and description. Maybe add all the other options that an embed has would be sick!

**Comment by aiko-chan-ai** [comment]
https://github.com/aiko-chan-ai/DiscordBotClient/blob/electron-v3/Vencord/src/plugins/botClient/index.ts#L627
u can make a pr

**Comment by aiko-chan-ai** [comment]
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/cc41a90d-8c1b-480f-9f20-5c72391ea13f)
