### ISSUE TITLE
not verifed bot shows up as a verifed bot

### ISSUE THREAD

**Issue by hakergeniusz** [aiko-chan-ai/DiscordBotClient#115]
![photo](https://github.com/aiko-chan-ai/DiscordBotClient/assets/117102435/197271b8-b63b-4af3-b5ac-e9d6c4fc7d7b)

**Comment by aiko-chan-ai** [comment]
it's not a bug, it's a feature

**Comment by aiko-chan-ai** [comment]
it can help botclient perform mod actions (verified account required)

**Comment by aiko-chan-ai** [comment]
btw fixed
