### ISSUE TITLE
LOGIN FAIL: MESSAGE_CONTENT IS REQUIRED

### ISSUE THREAD

**Issue by WlodekM** [aiko-chan-ai/DiscordBotClient#117]
![зображення](https://github.com/aiko-chan-ai/DiscordBotClient/assets/75479945/50d2ee94-36fd-43c9-add8-e520da4104ad)

**Comment by Wissididom** [comment]
You need to enable intents for your application on https://discord.dev. See #105

**Comment by WlodekM** [comment]
oh, thank you
