### ISSUE TITLE
[FEATURE REQUEST] Would it be possible to change avatars/banners of bots via the client

### ISSUE THREAD

**Issue by EthanWinters2885** [aiko-chan-ai/DiscordBotClient#119]
A small suggestion but today (as iof writing this) bots can now have avatars, and I wonder if it would be possible to beable to set animated pfps and banners in the app (I know you can just use the developer portal but still)

I know it's possible because it's possible to change usernames, avatars, banners, etc via like discord py, discord js etc

**Comment by aiko-chan-ai** [comment]
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/b24f9bc3-b9ea-4a4a-b59e-a4fb87b8bc68)

okie

**Comment by aiko-chan-ai** [comment]
v3.2.0 🎉

**Comment by EthanWinters2885** [comment]
Ayy epic!
