### ISSUE TITLE
cant see aiko chan command

### ISSUE THREAD

**Issue by deadgirl2** [aiko-chan-ai/DiscordBotClient#122]
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/151843222/43141db0-8246-4f65-a401-7f425225ce4b)
recent version, install : today
was i didnt do someting when install aiko chan?

**Comment by aiko-chan-ai** [comment]
I converted it to a built-in command, easier to use

**Comment by aiko-chan-ai** [comment]
All commands remain the same as before
