### ISSUE TITLE
Latest version (3.2.1) stays on gray loading screen

### ISSUE THREAD

**Issue by EthanWinters2885** [aiko-chan-ai/DiscordBotClient#123]
I tried opening the  app on the latest version and I only getting a gray screen.

![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/90074580/a6b47d31-40fe-4de6-868d-eed8ba243cb8)

**Comment by EthanWinters2885** [comment]
I am just going to stay on 3.2.0 until this bug is fixed, because I'd rather not have an unusable version

**Comment by aiko-chan-ai** [comment]
#8

**Comment by EthanWinters2885** [comment]
I've reinstalled twice, and reloaded several times, still nothing, also it just says "Loading vencord"

Am I essentially going to have to go through the hell of opening a virtual machine just to open this program?

Okay nevermind; I had to force turn off my pc by unplugging the whole pc

**Comment by aiko-chan-ai** [comment]
Did it work well?

**Comment by EthanWinters2885** [comment]
Yea

**Comment by Epicinver** [comment]
This still happens to me, i installed 2 weeks ago, tried everything, but it still dosent work.
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/171282660/7988091e-054b-42e8-92f2-f5d921a468a8)

**Comment by Spammer69420** [comment]
same why is it just a blank screen

**Comment by Epicinver** [comment]
idk
