### ISSUE TITLE
Can't Copy Anything

### ISSUE THREAD

**Issue by CasherGames** [aiko-chan-ai/DiscordBotClient#125]
i need A Copy bot Webhook URL But Dont Copying & using v3.2.1

**Comment by aiko-chan-ai** [comment]
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/13c3e1b8-2759-4780-a17b-4590e7649672)

**Comment by CasherGames** [comment]
https://drive.google.com/file/d/1niQUd9zXr73woLn1w6_lC-bN5pC6Qzjj/view?usp=sharing
see this video

**Comment by CasherGames** [comment]
i cant upload videos in github

**Comment by CasherGames** [comment]
when copy webhook URL Got A Error in Electron Console
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/86890809/ae86463d-fc83-462f-b46d-c020701b5c66)

**Comment by aiko-chan-ai** [comment]
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/83fd33b6-1087-44ec-94d9-9ee462e421df)
URL.canParse is a method only available with Chromium v120 (Electron v28)

**Comment by CasherGames** [comment]
but electron v28 not working for me

**Comment by CasherGames** [comment]
thanks for replay me , i found fix this issue
