### ISSUE TITLE
Requests sent keep getting blocked

### ISSUE THREAD

**Issue by MaxMady** [aiko-chan-ai/DiscordBotClient#13]
Unable to login... Token is right but its not being logged in.
The requests seems to get blocked

**Comment by aiko-chan-ai** [comment]
https://user-images.githubusercontent.com/71698422/210189290-f9c31386-e07a-49c5-b069-85c32ad8cac3.mp4

**Comment by aiko-chan-ai** [comment]
Have you used the extension yet?
