### ISSUE TITLE
so

### ISSUE THREAD

**Issue by ari00000000000** [aiko-chan-ai/DiscordBotClient#130]
hello! i have been soft locked from accessing the app due to the vencord setting called "showhiddenchannels" it breaks the entire app.

**Comment by misike12** [comment]
Then disable it

**Comment by ari00000000000** [comment]
Yes bro   Sent from Mail for Windows From: misike12Sent: Wednesday, April 10, 2024 10:17 AMTo: aiko-chan-ai/DiscordBotClientCc: ari00000000000; AuthorSubject: Re: [aiko-chan-ai/DiscordBotClient] so (Issue #130) Then disable it—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by misike12** [comment]
What?

**Comment by misike12** [comment]
Wait... ShowHiddenChannels is working for me
