### ISSUE TITLE
The app keeps requesting to download a new version, even if I installed it already

### ISSUE THREAD

**Issue by Nermal242** [aiko-chan-ai/DiscordBotClient#132]
Since version 3.2.1 was released, I get the popup to install that version everytime. However, even after running the updater for the new version, it still requests me to install the new version.

**Comment by Nermal242** [comment]
![So, for some reason, I'm still on an older version somehow even after running the installer for 3.2.1](https://github.com/aiko-chan-ai/DiscordBotClient/assets/56689711/34b26650-abe4-4ec6-9b92-77b372a43e70)

**Comment by aiko-chan-ai** [comment]
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/5b916c70-b9f1-471a-b748-c4cb04289392)
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/4dfdede6-a7b2-4d04-bc4c-26ce1bd1b574)

**Comment by Nermal242** [comment]
I have noticed that, however, how come the installer install an older version (or not updating it at all) when running it? Do i need to reinstall it completely to update it?

**Comment by Nermal242** [comment]
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/56689711/b3133dff-b04f-4f85-b88f-f0484464c10d)
So once i run the installer, it opens the correct version, but when closing and reopening the app from the taskbar I get the older version again which sends me to the github download page again.

**Comment by Nermal242** [comment]
Nevermind, I solved it (the shortcut on the taskbar was from a different version which was installed on a different user and not updated). This was an issue on my end.

**Comment by aiko-chan-ai** [comment]
=))
