### ISSUE TITLE
[SUGGESTION] Allow bots to use polls

### ISSUE THREAD

**Issue by EthanWinters2885** [aiko-chan-ai/DiscordBotClient#134]
As of writing this post, the polls features has rolled out to everyone and I think bots MIGHT beable to use them too

**Comment by Wissididom** [comment]
They will, but it is not documented yet: `https://togithub.com/discord/discord-api-docs/pull/6746`

**Comment by aiko-chan-ai** [comment]
when this feature is officially launched and I will update the client

**Comment by aiko-chan-ai** [comment]
v3.3.0 🎉

**Comment by aiko-chan-ai** [comment]
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/54898483-fb1b-42c1-841c-2b335a93462c)
