### ISSUE TITLE
Make it show all servers in the bot not just 100 or 200

### ISSUE THREAD

**Issue by Alon122** [aiko-chan-ai/DiscordBotClient#135]
Make it show all servers in the bot not just 100 or 200

**Comment by aiko-chan-ai** [comment]
Why ?

**Comment by Alon122** [comment]
What do you mean why, why not.

בתאריך יום ג׳, 16 באפר׳ 2024, 13:04, מאת Elysia ***@***.***>:

**Comment by aiko-chan-ai** [comment]
https://github.com/aiko-chan-ai/DiscordBotClient/issues/89#issuecomment-1921459464
