### ISSUE TITLE
Not Loading ?

### ISSUE THREAD

**Issue by ggmaster200** [aiko-chan-ai/DiscordBotClient#138]
![anydesk00002](https://github.com/aiko-chan-ai/DiscordBotClient/assets/167584199/da28cbf3-9297-4363-ab6f-086a8d4eaa01)

**Comment by ggmaster200** [comment]
no one

**Comment by aiko-chan-ai** [comment]
U should open devtools

**Comment by ggmaster200** [comment]
yes , console not see any errors
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/167584199/8d207611-6c78-4209-a345-51475ea184bf)
