### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by iGetUploaded** [aiko-chan-ai/DiscordBotClient#14]
Getting this error when I do npm i 

![image](https://user-images.githubusercontent.com/54633753/210443924-91fdab8b-8a51-46c4-96de-1d524e6fa40f.png)

**Comment by aiko-chan-ai** [comment]
Did you move to the correct directory?

**Comment by iGetUploaded** [comment]
Sorry for late response I did get it to work now I was in the right directory must of missed it thanks tho
