### ISSUE TITLE
Account change system

### ISSUE THREAD

**Issue by Sedonya** [aiko-chan-ai/DiscordBotClient#141]
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/115283299/4f68d0db-4ea1-4fa0-a415-6b11ef67c71e)
At the moment the bot client does not save the bots I logged in, and if I click “Add account” it does not ask for a token but email and password.
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/115283299/952ba27d-c842-40b1-9ec8-f9305aada69c)

**Comment by moxie-coder** [comment]
use the slash command “switchtoken”

**Comment by Sedonya** [comment]
Bro, I know about this command, but I'm offering you a new idea, not looking for a way to solve a problem, besides switchtoken doesn't remember them

**Comment by aiko-chan-ai** [comment]
👍

**Comment by aiko-chan-ai** [comment]
If i can patch the UI

**Comment by aiko-chan-ai** [comment]
v3.3.0 🎉
