### ISSUE TITLE
suggestion: add ability to log into multiple bots

### ISSUE THREAD

**Issue by rech2020** [aiko-chan-ai/DiscordBotClient#144]
right now it looks something like this and because you need for some reason a login and a password you cant really log into a second account
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/131972043/ecc9da35-b453-48cd-a27b-d6c0f3423201)

or can you?

**Comment by moxie-coder** [comment]
just use the `switchtoken` slash command

**Comment by rech2020** [comment]
oh thanks

**Comment by Sedonya** [comment]
> просто используйте команду `switchtoken` slash

https://github.com/aiko-chan-ai/DiscordBotClient/issues/141#issuecomment-2141019360

**Comment by aiko-chan-ai** [comment]
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/bef853e7-0bb8-45e7-a611-1964a50c9e97)

Will be available in the next version

**Comment by aiko-chan-ai** [comment]
v3.3.0 🎉
