### ISSUE TITLE
Fails to open on MacOS

### ISSUE THREAD

**Issue by LumiFae** [aiko-chan-ai/DiscordBotClient#145]
<img width="267" alt="image" src="https://github.com/aiko-chan-ai/DiscordBotClient/assets/54886938/325818c9-befd-4dc4-93b2-ce3a40d9963c">

M3 Pro - Macbook Pro
18GB RAM

**Comment by aiko-chan-ai** [comment]
u should build from source

`npm install`
`npm run mac`

**Comment by GillHoang** [comment]
```
git clone https://github.com/aiko-chan-ai/DiscordBotClient.git
cd DiscordBotClient
npm run requirement
npm run build
```
try it

**Comment by LumiFae** [comment]
Just got round to needing this again, just did the installation stuff, worked fine for me. If you need the build, let me know!
