### ISSUE TITLE
Embed Error in Latest version

### ISSUE THREAD

**Issue by moxie-coder** [aiko-chan-ai/DiscordBotClient#147]
```
TypeError: fR.post is not a function
    at Object.execute (VencordWeb:220:715)
    at Object.KC (VencordWeb:19:54)
    at F (WebpackModule667204:2:5849)
    at async eval (WebpackModule287746:2:7208)
```
This happened when trying to make an embed

**Comment by aiko-chan-ai** [comment]
ohno!

**Comment by aiko-chan-ai** [comment]
resolved, please wait for the upcoming update

**Comment by moxie-coder** [comment]
> resolved, please wait for the upcoming update

awesome!

**Comment by aiko-chan-ai** [comment]
> awesome!

fun fact: new UI for embed generator
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/5520a1b0-3f00-4cdb-aaee-59a4abbe2d4d)

**Comment by aiko-chan-ai** [comment]
demo:

![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/547fcd56-c378-41c5-acc2-81da8063ab70)

![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/460ff2b8-e92b-4c98-a375-2871194aa19f)

![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/14d86959-5827-4a05-b33a-f3142fbb24fb)

#112 #50

**Comment by aiko-chan-ai** [comment]
actually I just learned React 5 hours ago

**Comment by ggmaster200** [comment]
who release it

**Comment by aiko-chan-ai** [comment]
> where release it

nowww
