### ISSUE TITLE
Stop the forum channels popup

### ISSUE THREAD

**Issue by CalebUSA** [aiko-chan-ai/DiscordBotClient#148]
Is there any way you can stop the forum channels popup that pops up any time you open up the discord client or if it has been sitting for a bit and you click on a channel?
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/29007834/d6b6f1f5-a5ce-4f4f-92d7-2dca818c8d2b)

**Comment by aiko-chan-ai** [comment]
I tried several approaches but still not working (maybe the next update will solve it)

**Comment by aiko-chan-ai** [comment]
fixed
