### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by eksekjut** [aiko-chan-ai/DiscordBotClient#15]
There is problem when trying to login. After you put your token the page will just reload and change to defualt login page!
![image](https://user-images.githubusercontent.com/81157619/213947169-6e9fa078-c917-4e9f-8e5b-6729ece9cb6a.png)

**Comment by aiko-chan-ai** [comment]
Try ctrl+shift+i (devtools)
```js
getModule('loginToken').loginToken(urToken)
```

**Comment by aiko-chan-ai** [comment]
you can reload the page, the error is caused by the wrong token
