### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by jsinc-sebastian** [aiko-chan-ai/DiscordBotClient#150]
Does the application respect privacy? Not sure if I really trust this tool still that it works.

**Comment by moxie-coder** [comment]
yeah it does, it's open source btw

**Comment by jsinc-sebastian** [comment]
Okay. Thank you for the reply!

**Comment by aiko-chan-ai** [comment]
I don't store anything (the localhost server also just runs on your machine), except the index.html file downloaded from github
