### ISSUE TITLE
Channel read status and DM's reset on relaunch 

### ISSUE THREAD

**Issue by approxit1** [aiko-chan-ai/DiscordBotClient#152]
Great app. but, from what I've experienced so far, when you relaunch the client; 
- The read status of channels reappears as if they were never marked as read.
- Direct messages with users do not save and reset to an earlier state

**Comment by aiko-chan-ai** [comment]
Discord doesn't save this data for bot accounts, I could implement it but it would be pretty bad, trust me

**Comment by approxit1** [comment]
i'll try implementing a solution to save direct messages as that seems feasible to add. Do you think it's possible without making it bad or anything?

**Comment by aiko-chan-ai** [comment]
I will try tomorrow

**Comment by aiko-chan-ai** [comment]
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/27528e92-23d3-4d3b-ba0b-48e6404f8aaf)

**Comment by aiko-chan-ai** [comment]
At least it saves private channels
