### ISSUE TITLE
App does not start

### ISSUE THREAD

**Issue by miguelmeier** [aiko-chan-ai/DiscordBotClient#155]
I've tried everything
I've tried reinstalling it but it doesn't work. When I start the app there's just a grey screen that doesn't go away

**Comment by moxie-coder** [comment]
can you show the console?

**Comment by miguelmeier** [comment]
![image](https://github.com/user-attachments/assets/e5395ab6-4e16-47d7-8dd9-94220f3bebbb)

**Comment by melvin230410** [comment]
there is not I waited 10 minutes

**Comment by miguelmeier** [comment]
there is not I waited 10 minutes
