### ISSUE TITLE
"Well This Is Awkward" MacOS Issue

### ISSUE THREAD

**Issue by ghost** [aiko-chan-ai/DiscordBotClient#156]
Hello, whenever I open the application and put in the token, it comes up with a crash message. I use MacOS.

![image](https://github.com/user-attachments/assets/d6109f70-a832-4bf0-910c-cf20961ab38c)

**Comment by ghost** [comment]
![image](https://github.com/user-attachments/assets/ccfe55fb-5dfd-4034-a5a3-0633f7292711)

**Comment by aiko-chan-ai** [comment]
;_;

**Comment by aiko-chan-ai** [comment]
Are you using the official version or building from source ?

**Comment by ghost** [comment]
> Are you using the official version or building from source ?

Built.

**Comment by aiko-chan-ai** [comment]
There may have been an error during the previous implementation of feature #152  ;-;

**Comment by aiko-chan-ai** [comment]
I will continue this issue until there is an official update
