### ISSUE TITLE
[SUGGESTION] Reply with embeds

### ISSUE THREAD

**Issue by mostidaniel** [aiko-chan-ai/DiscordBotClient#159]
Currently, it's not possible to reply messages with embeds. The embed tool just posts new messages.

**Comment by aiko-chan-ai** [comment]
ok

**Comment by aiko-chan-ai** [comment]
![image](https://github.com/user-attachments/assets/df67dc7d-efdb-4aa9-8a6b-2b178a8a0a74)
next release

**Comment by mostidaniel** [comment]
> ![image](https://github.com/user-attachments/assets/df67dc7d-efdb-4aa9-8a6b-2b178a8a0a74)
> next release

Thank you very much! Please take your time
