### ISSUE TITLE
Where is the web version

### ISSUE THREAD

**Issue by eyadelhosiny** [aiko-chan-ai/DiscordBotClient#160]
I can't access the web version. If it isn't available now, how can I host my own? Is the code open source?

**Comment by aiko-chan-ai** [comment]
I really do not recommend using the Web version, as handling the API is very complex and may cause the application to crash.

If you prefer using the Web version, please use this website: https://chriseric1.github.io/ (Not related to me, use at your own risk).

You can localhost my version, but it requires modifications with the Vencord extension (new version) or using branch 161052 (previous old Web version).

The old version uses unsupported extensions, which may no longer be usable.

**Comment by Epicinver** [comment]
i enter it, mcaffe says it is a phishing website, and shows a red screen

**Comment by Natemo2625** [comment]
@Epicinver it seems like any github.io site is marked as a phishing site now, as my github page for my bot has also been flagged recently. I'm not saying it definitely isn't, but a lot of them have been falsely flagged.
