### ISSUE TITLE
[FEATURE REQUEST] maybe add a way to use emojis that the bot has uplaoded to them??

### ISSUE THREAD

**Issue by EthanWinters2885** [aiko-chan-ai/DiscordBotClient#162]
discord bots can now have custom emojis without servers

![image](https://github.com/user-attachments/assets/76e0af05-46eb-4f8d-aee1-abdaa8ece89c)

**Comment by aiko-chan-ai** [comment]
ik ;-;

**Comment by thedtvn** [comment]
@EthanWinters2885 That emojis just that bot and webhook can use

**Comment by aiko-chan-ai** [comment]
![image](https://github.com/user-attachments/assets/125d7b3a-3554-4086-a7f4-7877ecc6b8fd)
![image](https://github.com/user-attachments/assets/53c2bdf2-7100-44bc-b9a9-5586f5833ba0)
I’ve tried implementing it, but assigning emojis to the emoji picker window is very challenging (involves multiple modules). At least for now, you can still use the emoji search feature in the chat box to send these emojis.

**Comment by aiko-chan-ai** [comment]
![image](https://github.com/user-attachments/assets/c5ab4c3d-e4a0-4bcb-9fe5-43e3b426a268)
