### ISSUE TITLE
Gray screen when opening DiscordBotClient v3.4.1

### ISSUE THREAD

**Issue by WeeboChan** [aiko-chan-ai/DiscordBotClient#163]
As title, the client just opens a gray screen, cannot interact with it or close it.
Have to use task manager to close the application.

See following:
![image](https://github.com/user-attachments/assets/b6461d07-3f2a-4e3c-95f8-cd18e760e4a7)

**Comment by aiko-chan-ai** [comment]
![image](https://github.com/user-attachments/assets/90502211-f079-4f9b-a8ef-23c3db253541)
![image](https://github.com/user-attachments/assets/2ff7673d-e2b0-4ff4-8fb4-ac416878238e)
Use this menu
It seems your internet is not good

**Comment by SetAsync** [comment]
I'm having the same issue, but I can close the window as normal. Also experienced this issue with the original version of this software.

**Comment by immason29** [comment]
Same thing here, normal top bar but nothing showing up except blank.

**Comment by aiko-chan-ai** [comment]
#8
