### ISSUE TITLE
Patche failure of some Vencord plugins

### ISSUE THREAD

**Issue by huangnana520** [aiko-chan-ai/DiscordBotClient#165]
Patche failure of some Vencord plugins discovered through debugging https://canary.discord.com/assets/web.4ad71637962adaebda42.js This file was loaded earlier than https://canary.discord.com/channels/VencordWeb

**Comment by aiko-chan-ai** [comment]
Currently, versions of Vencord and BotClient have not yet been updated to the latest version of Discord.

**Comment by Guineawoof** [comment]
ok?

**Comment by huangnana520** [comment]
> Currently, versions of Vencord and BotClient have not yet been updated to the latest version of Discord.

The issue with the loading order can be consistently reproduced after executing the win.webContents.reload() operation.

**Comment by aiko-chan-ai** [comment]
It may have been fixed in the latest version.
