### ISSUE TITLE
Search server

### ISSUE THREAD

**Issue by yeci226** [aiko-chan-ai/DiscordBotClient#166]
As the title says, if I want to search for a specific server among many servers, I have to search one by one.

**Comment by yeci226** [comment]
btw, if you can hope to continuously display the current Shard ID somewhere to avoid forgetting and switching the same shard again

**Comment by holymode** [comment]
I agree, its a much needed feature. You have to switch shards any manually search the server since you have no idea which shard its on. 

I know you open it via invite url but you dont always have a invite url to the server you need (depending on bot perms).

**Comment by aiko-chan-ai** [comment]
Since Discord does not have an API to retrieve all guilds, the guilds can only be obtained from the Gateway. However, because sharding divides the guilds, there is no easy way to search for servers. If you know the server ID, then you can search for it.

**Comment by yeci226** [comment]
> Since Discord does not have an API to retrieve all guilds, the guilds can only be obtained from the Gateway. However, because sharding divides the guilds, there is no easy way to search for servers. If you know the server ID, then you can search for it.

That's exactly why I created this issue, I don't know where to find the server using the Discord server id 🥵

**Comment by aiko-chan-ai** [comment]
#183

**Comment by aiko-chan-ai** [comment]
`/switchguild` 👍
