### ISSUE TITLE
macos app broken.

### ISSUE THREAD

**Issue by amah853** [aiko-chan-ai/DiscordBotClient#167]
message when running: "“DiscordBotClient” is damaged and can’t be opened. You should eject the disk image."

**Comment by aiko-chan-ai** [comment]
![image](https://github.com/user-attachments/assets/5ff61f54-ca66-4292-a0a6-9c27acdb81a3)
https://github.com/aiko-chan-ai/DiscordBotClient/issues/145

**Comment by amah853** [comment]
hey,
Yes, I saw that. I am using Apple Silicon.

**Comment by aiko-chan-ai** [comment]
Because I don't have a Mac, if there are errors from the build, I won't really know. Instead, please build it yourself.
