### ISSUE TITLE
Screen share doesent work

### ISSUE THREAD

**Issue by ImDogal** [aiko-chan-ai/DiscordBotClient#171]
when i try to see a screen that some one is sharing it doesent load the screen

**Comment by moxie-coder** [comment]
> when i try to see a screen that some one is sharing it doesent load the screen

bots can't screenshare

**Comment by ImDogal** [comment]
> > when i try to see a screen that some one is sharing it doesent load the screen
> 
> bots can't screenshare

i want to see not share a screenshare

**Comment by moxie-coder** [comment]
> > > when i try to see a screen that some one is sharing it doesent load the screen
> > 
> > 
> > bots can't screenshare
> 
> i want to see not share a screenshare

they have no way of viewing screenshares

**Comment by ImDogal** [comment]
> > > > when i try to see a screen that some one is sharing it doesent load the screen
> > > 
> > > 
> > > bots can't screenshare
> > 
> > 
> > i want to see not share a screenshare
> 
> they have no way of viewing screenshares

that makes sense
