### ISSUE TITLE
[FEATURE REQUEST] maybe make buttons and embeds in messages

### ISSUE THREAD

**Issue by ImDogal** [aiko-chan-ai/DiscordBotClient#172]
it would be nice to create embeds and custom buttons

**Comment by 1234coco** [comment]
good idea :))

**Comment by 1234coco** [comment]
but what you will do with button in embed?

**Comment by aiko-chan-ai** [comment]
=))

**Comment by ImDogal** [comment]
> but what you will do with button in embed?

Embed AND buttons, not buttons in embeds

**Comment by ImDogal** [comment]
Would also be nice to put custom commands(in JavaScript or python) in the button (when clicked)

**Comment by EthanWinters2885** [comment]
Think they mean URL buttons primarily.

**Comment by aiko-chan-ai** [comment]
#183

**Comment by aiko-chan-ai** [comment]
I don't have a design idea for the interface to send the button, as the button depends on ActionRow, making the implementation quite complex.
