### ISSUE TITLE
Immediate Crash upon opening

### ISSUE THREAD

**Issue by Spigey** [aiko-chan-ai/DiscordBotClient#177]
Whenever I try to open DiscordBotClient, it immediately crashes and I get this error in the console:
VM2191 43455.25f3dd89fa027ef12b67.js:23 Failed to parse settings from localStorage:  TypeError: Cannot read properties of undefined (reading 'getItem')
    at Object.get (VencordWeb:477:1325)
    at VencordWeb:18:25829
    at VencordWeb:5:497
    at VencordWeb:23:6387
    at VencordWeb:5:497
    at VencordWeb:23:6880
    at VencordWeb:5:497
    at VencordWeb:432:37863
    at VencordWeb:5:497
    at VencordWeb:432:41428
    at VencordWeb:5:497
    at VencordWeb:432:41916
    at VencordWeb:5:497
    at VencordWeb:440:2503
    at VencordWeb:5:497
    at VencordWeb:477:1563
    at VencordWeb:477:1584

I have also tried reinstalling it multiple times, restarting my computer, etc

**Comment by aiko-chan-ai** [comment]
I can't reproduce this error, as it occurs very randomly, because the extension starts after Discord has already overridden localStorage.

**Comment by Spigey** [comment]
I've been having this issue constantly for the past 2 days. It worked for about 10 minutes until I restarted the app again.

**Comment by aiko-chan-ai** [comment]
I’m back after a while.
This issue also occurs with the official client, and I currently don’t have a complete workaround.
