### ISSUE TITLE
can't launch the app

### ISSUE THREAD

**Issue by threetpot** [aiko-chan-ai/DiscordBotClient#179]
Can't launch discord bot client with the error: "The procedure entry point DiscardVirtualMemory could not be located in the dynamic link library KERNEL32.dll."

pls fix it

**Comment by moxie-coder** [comment]
what version of Windows are you running?

**Comment by threetpot** [comment]
windows 7

**Comment by Forbirdden** [comment]
> windows 7

It`s because DBC work on Electron, Electron uses Chromium, Chromium stopped support Windows 7 at version 109, try DBC version 2.4.2, but some features will be unavailable

**Comment by moxie-coder** [comment]
> windows 7

Windows 7 isn’t compatible with the newer versions because electron stopped supporting windows 7 a long time ago

**Comment by threetpot** [comment]
ok thanks i know now
