### ISSUE TITLE
DMs won`t show

### ISSUE THREAD

**Issue by Forbirdden** [aiko-chan-ai/DiscordBotClient#181]
After restarting DBC all people from DMs just disappearing until you manually go to DMs from their profile 
![image](https://github.com/user-attachments/assets/294116a5-bf73-4069-8c0f-48060e9bde0c)

**Comment by moxie-coder** [comment]
it doesn't save data, because bots can't save user data

**Comment by aiko-chan-ai** [comment]
Which version are you using?

**Comment by Forbirdden** [comment]
> Which version are you using?

3.4.1 and 2.4.2

**Comment by aiko-chan-ai** [comment]
I'm currently in the process of updating the application to the latest version, so I'll have to deal with this error afterward ;-;
![image](https://github.com/user-attachments/assets/9e0cec4a-46e3-40da-9e49-ced5012ff34c)

**Comment by Forbirdden** [comment]
> I'm currently in the process of updating the application to the latest version, so I'll have to deal with this error afterward ;-; ![image](https://private-user-images.githubusercontent.com/71698422/371527133-9e0cec4a-46e3-40da-9e49-ced5012ff34c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0NDQzMDksIm5iZiI6MTcyNzQ0NDAwOSwicGF0aCI6Ii83MTY5ODQyMi8zNzE1MjcxMzMtOWUwY2VjNGEtNDZlMy00MGRhLTllNDktY2VkNTAxMmZmMzRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDEzMzMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ZDJjMGQ3YThmMDNkMmU2YWE1YmVlYTM2ZmU3NWNkNDI4MDU4NTRlN2ZhNGQ4YzlmN2U3YzBmMzIzZjI4NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.M6oSa97KphJxtuFmlhXjIel1sJc8skbwxMSmkFlI1ic)

Ok, thanks!

**Comment by aiko-chan-ai** [comment]
#183

**Comment by aiko-chan-ai** [comment]
oops

**Comment by estrogened** [comment]
@aiko-chan-ai I have a suggestion listen for message create in dms so you can make dms appear. rn if i dm my bot while bot client is open it doesnt add the dm to the dms list but that should be possible.
