### ISSUE TITLE
[Update] Discord Build 331146 & Vencord v1.10.3

### ISSUE THREAD

**Issue by aiko-chan-ai** [aiko-chan-ai/DiscordBotClient#183]
#### Here is the todo (track list) for this update, including what I've done, known issues (that won't be fixed soon), and features that will be available. Everyone can also add features here.

- [x] Login with bot token
    - [x] Avoid user account login
    - [x] Logout
    - [x] Remove/Patch unused bot ws opcode
        - [x] Patch updateGuildSubscriptions Event
        - [x] Patch send updateGuildSubscriptions
    - [x] Leave / Switch VoiceChannel
    - [x] Patch identify & events
        - [x] Patch close code
        - [x] Patch events
            - [x] Patch MESSAGE_CREATE / CHANNEL_CREATE / READY_SUPPLEMENTAL / READY (_handleDispatch)
            - [x] Patch intents
            - [x] Sharding & switch guild (https://github.com/aiko-chan-ai/DiscordBotClient/issues/166#issuecomment-2322839377)
- [x] Patch getToken & setToken
- [x] Patch onboarding
- [x] Patch modules
    - [x] Patch acceptInvite
    - [x] Patch loadTemplatesForGuild
    - [x] Patch copy URL
    - [x] Patch message attachment size (25mb)
    - [x] Relationships Module
    - [x] Search Emojis (Application Emojis)
- [x] Patch UI
    - [x] Remove QRLogin
    - [x] Add Login with Token
    - [x] Add Login with Token (Switch account modal) Known issue: When you enter an incorrect token while switching accounts, overlapping elements may occur.
    - [x] Embed Editor
        - [x] Chatbar
        - [x] Message button
        - [ ] JSON editor / Button ?
- [x] Handle Private Channel
- [x] Patch getOldestUnread / hasUnread
- [ ] Thread (Known issue)
    - [x] Search threads: It cannot be perfectly implemented due to API limitations (Sorting only - 50 threads max)
    - [x] Text channel
    - [ ] Forum channel: Only the list view can be used, as the gallery view has display issues (threads do not appear at the top of the page).
    - [ ] Media channel: The display issue with threads is due to the gallery view being set as the default.
- [x] Electron features
    - [x] Save direct message
    - [x] Clear DMs cache
    - [x] User Settings
    - [x] More API
- [ ] any...

**Comment by Forbirdden** [comment]
I`m ready to make new update work on old windows :)

**Comment by aiko-chan-ai** [comment]
> I`m ready to make new update work on old windows :)

Sure, you can try =))

**Comment by Forbirdden** [comment]
As i can see that`s gonna be a big update 
![pigeonpls-pigeon-dance](https://github.com/user-attachments/assets/5c183ed5-980f-4642-9452-46df27914bec)

**Comment by aiko-chan-ai** [comment]
![image](https://github.com/user-attachments/assets/71126475-1bfe-422f-a274-00b05e972f79)

I hate this bug.

**Comment by Forbirdden** [comment]
> ![image](https://private-user-images.githubusercontent.com/71698422/371768187-71126475-1bfe-422f-a274-00b05e972f79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MzY0NTAsIm5iZiI6MTcyNzUzNjE1MCwicGF0aCI6Ii83MTY5ODQyMi8zNzE3NjgxODctNzExMjY0NzUtMWJmZS00MjJmLWEyNzQtMDBiMDVlOTcyZjc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI4VDE1MDkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3MzIxMDFiY2M4ODUxNGM1MjQyYzg0OTIxZDliMDJmZDEwMzY4MGEwNDVjZWNiODc3ZjVjOGVmOTI1Njg3YmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CcvRsI5fLUUj3qO21t0iVoIIDfvnaIhShtF7rrSmdUQ)
> 
> I hate this bug.

![image](https://github.com/user-attachments/assets/e317a31f-0a86-4772-bd72-1c72dee82e3c)
![calaca-insana-skull-insane (1)](https://github.com/user-attachments/assets/f6f70f89-fa5b-4f5d-832f-b5067e7852f4)

**Comment by aiko-chan-ai** [comment]
> Some communities in Vietnam are very interesting.

**Comment by Forbirdden** [comment]
> > Some communities in Vietnam are very interesting.

 There is a Vietnamese clothing store named "BiBo shop" 15 km away from me

**Comment by Forbirdden** [comment]
YAY

**Comment by aiko-chan-ai** [comment]
speedrun ;-;

**Comment by Forbirdden** [comment]
> > I`m ready to make new update work on old windows :)
> 
> Sure, you can try =))

1st snapshot is ready

**Comment by Forbirdden** [comment]
> > > I`m ready to make new update work on old windows :)
> > 
> > 
> > Sure, you can try =))
> 
> 1st snapshot is ready

AND IT`S EVEN WORKING

**Comment by Forbirdden** [comment]
> > > > I`m ready to make new update work on old windows :)
> > > 
> > > 
> > > Sure, you can try =))
> > 
> > 
> > 1st snapshot is ready
> 
> AND IT`S EVEN WORKING

huh
![image](https://github.com/user-attachments/assets/475d14e0-8f03-4f7b-b7a5-c9a118ff5cec)

**Comment by aiko-chan-ai** [comment]
=))

**Comment by Forbirdden** [comment]
> =))

![image](https://github.com/user-attachments/assets/ee82cc3c-1738-45a3-9844-b32999639ae3)

**Comment by aiko-chan-ai** [comment]
If you are using an older version of Discord, the new version of Vencord will not work properly.

**Comment by Forbirdden** [comment]
> If you are using an older version of Discord, the new version of Vencord will not work properly.

Somehow i got there...
![image](https://github.com/user-attachments/assets/a75df61d-5432-46fb-a8ae-46941f091ff4)

**Comment by Forbirdden** [comment]
> > If you are using an older version of Discord, the new version of Vencord will not work properly.
> 
> Somehow i got there... ![image](https://private-user-images.githubusercontent.com/102984166/371777040-a75df61d-5432-46fb-a8ae-46941f091ff4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1OTYxMDUsIm5iZiI6MTcyNzU5NTgwNSwicGF0aCI6Ii8xMDI5ODQxNjYvMzcxNzc3MDQwLWE3NWRmNjFkLTU0MzItNDZmYi1hOGFlLTQ2OTQxZjA5MWZmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQwNzQzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDUyNDIyNzI4OWYzODQ5NDhjM2ZhZjNiMTZjMjU3MTVhMzY0Y2Y5MGRhOTA3ZDNkZmM4MTg3ZDhiY2UwMGY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZUm21N_QNeQFZNHacUWue0ZmkRjH9dKX_0k8uDTE9B0)

I made a working snapshot, but it shows an incorrect version
![image](https://github.com/user-attachments/assets/8e2482e1-bf8c-4a91-998d-2e1f5cf6ab03)
![image](https://github.com/user-attachments/assets/25abae42-b446-4f87-96e8-4be908096de1)
![image](https://github.com/user-attachments/assets/63b40b41-faf5-4c83-ac66-039a0beec25d)

**Comment by aiko-chan-ai** [comment]
=))

**Comment by aiko-chan-ai** [comment]
btw @Forbirdden you can use Electron v22 instead of Electron v15
ref: https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice

**Comment by Forbirdden** [comment]
> btw @Forbirdden you can use Electron v22 instead of Electron v15 ref: https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice

I'm already using it

**Comment by Forbirdden** [comment]
> > btw @Forbirdden you can use Electron v22 instead of Electron v15 ref: https://www.electronjs.org/blog/windows-7-to-8-1-deprecation-notice
> 
> I'm already using it

Just testing how different features works on different versions of electron

**Comment by Forbirdden** [comment]
> =))

Do you know how to fix it?
