### ISSUE TITLE
User login

### ISSUE THREAD

**Issue by Forbirdden** [aiko-chan-ai/DiscordBotClient#184]
I can\`t login into bot account, there isn\`t any token login here
![image](https://github.com/user-attachments/assets/5bdbcee2-c0fe-462f-ae2a-7fde0e7b51f6)

**Comment by aiko-chan-ai** [comment]
Only the recent version using Vencord is patched directly by me with React, while the previous versions all used JS DOM.

**Comment by Forbirdden** [comment]
> Only the recent version using Vencord is patched directly by me with React, while the previous versions all used JS DOM.

I`m using newest Vencord from this repo
![image](https://github.com/user-attachments/assets/9689b304-a535-4d11-b459-4195e174894a)

**Comment by aiko-chan-ai** [comment]
> I`m using newest Vencord from this repo ![image](https://private-user-images.githubusercontent.com/102984166/371779728-9689b304-a535-4d11-b459-4195e174894a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1NDQ1NjYsIm5iZiI6MTcyNzU0NDI2NiwicGF0aCI6Ii8xMDI5ODQxNjYvMzcxNzc5NzI4LTk2ODliMzA0LWE1MzUtNGQxMS1iNDU5LTQxOTVlMTc0ODk0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOFQxNzI0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZTVjZDViYjk4MzE2OTMzMGMxOTQ0MmQ5MDI2YzA2Y2RhOTQ0MDA4MzY0MGQyNzZjMzJjYzk4YjZlOGRjZjA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qfQTQ-dHiXeggwSsSDEiqqFXsWCZCRvsBjPBlZVnZiE)

![image](https://github.com/user-attachments/assets/3cb6de53-b6f5-4dd1-a571-ead74acad4dc)

nah

**Comment by Forbirdden** [comment]
Okay i fixed it
