### ISSUE TITLE
Can't connect to discord

### ISSUE THREAD

**Issue by Ayush-jaiswal234** [aiko-chan-ai/DiscordBotClient#191]
![Screenshot 2024-10-21 100055](https://github.com/user-attachments/assets/d1ad2ce6-205d-4444-9b7e-a3eb504f1bc6)
Getting this screen after entering the bot token to login, tried the common fixes with no help

**Comment by aiko-chan-ai** [comment]
Can u screenshot devtool screen:?

**Comment by Ayush-jaiswal234** [comment]
Not sure this is the screenshot you are looking for but let me know what you are exactly asking for 
![image](https://github.com/user-attachments/assets/4d7fecc5-7d81-4c8b-80d1-7e6c4f235f16)
![image](https://github.com/user-attachments/assets/93101eb6-9a92-48fe-8046-8bfc21fba356)

**Comment by aiko-chan-ai** [comment]
I will look into it

**Comment by aiko-chan-ai** [comment]
![image](https://github.com/user-attachments/assets/13de23fe-5cb1-4664-87cd-700ea0b0847f)
I've tried very hard, but I can't reproduce this error. Could you try clearing your web cache?

**Comment by Ayush-jaiswal234** [comment]
that solved it, one to wonder why reinstalling the entire thing didn't solve the problem tho

Thanks for the help

**Comment by Ayush-jaiswal234** [comment]
I also want to add that i have to do clear web storage everytime to log in or it justs crashes everytime

**Comment by aiko-chan-ai** [comment]
That's strange

**Comment by aiko-chan-ai** [comment]
I've figured out the reason why it's happening.

Did you rearrange the server list?

**Comment by Ayush-jaiswal234** [comment]
I can't recall that but if it should be in the order of which it joined first and second and so on, then yeah it appears to be random. And it looks like i am able to login without having to clear web storage anymore

**Comment by aiko-chan-ai** [comment]
;-;

**Comment by aiko-chan-ai** [comment]
fixed
