### ISSUE TITLE
BetterDiscord?

### ISSUE THREAD

**Issue by legacy1477** [aiko-chan-ai/DiscordBotClient#196]
Anyway to make BD work with this? I tried hooking it in a few js files, but didn't work.
I don't really use vencord and they seem to hate the idea of editusers which is the only plugin I'd like to use.
If BD is currently incompatible are there any plans to make it compatible/include it in future releases?

**Comment by aiko-chan-ai** [comment]
If Better Discord had a web version, I would integrate it into this application

**Comment by legacy1477** [comment]
Hey, apologies in advance if this is annoying. Even if not for release, is it possible to somehow hook Tampermonkey or execute userscripts in the client to swap out images? Vancord allows for live editing css and I somewhat managed to do this to a small buggy extent, but would like to make it a lot less buggy and more customizable. If no, any chance you could build in a native image redirect feature? Not asking to replicate editusers, but more of so just to replace pfp's and banners.
