### ISSUE TITLE
What is "sentry.4aa65d8….js:14 [GatewaySocket] [RESET] (true, 4004, MESSAGE_CONTENT is required)"

### ISSUE THREAD

**Issue by Sysdriver0** [aiko-chan-ai/DiscordBotClient#202]
so i wanted to login into my bot and i get this error: sentry.4aa65d8….js:14 [GatewaySocket] [RESET] (true, 4004, MESSAGE_CONTENT is required)

**Comment by moxie-coder** [comment]
You need intents enabled on your bot

**Comment by Sysdriver0** [comment]
> You need intents enabled on your bot

oh thanks

**Comment by Sysdriver0** [comment]
ty
