### ISSUE TITLE
bug: long freeze on account switch

### ISSUE THREAD

**Issue by lillithrosepup** [aiko-chan-ai/DiscordBotClient#207]
When i use the discord account switcher and enter another bot's token, it freezes for about 30 seconds. The last thing i see in the console is the READY event being logged, but i cannot click it to expand

**Comment by Danny09876** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by aiko-chan-ai** [comment]
fixed
