### ISSUE TITLE
Help pls

### ISSUE THREAD

**Issue by Noobonprovam** [aiko-chan-ai/DiscordBotClient#21]
![image](https://user-images.githubusercontent.com/86569492/232709892-bb2d6191-4d05-4c6b-94d0-65be21fe0f52.png)
And stop bot

**Comment by aiko-chan-ai** [comment]
Esc

**Comment by Noobonprovam** [comment]
dont work((

**Comment by aiko-chan-ai** [comment]
💀

**Comment by Noobonprovam** [comment]
go in discord

**Comment by aiko-chan-ai** [comment]
fixed (v2.1.1)
