### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by DatUub** [aiko-chan-ai/DiscordBotClient#210]
![{7910A767-7CD1-45D8-95FB-2DC37E418962}](https://github.com/user-attachments/assets/68a6c555-1f2d-401b-9163-a90e44b0230c)

**Comment by aiko-chan-ai** [comment]
yep, ik
I am working to fix this error

**Comment by aiko-chan-ai** [comment]
fixed!

**Comment by aiko-chan-ai** [comment]
![image](https://github.com/user-attachments/assets/7189e4ce-a7f1-41c0-b930-e2ade064b893)
