### ISSUE TITLE
Adding linux build to the release page

### ISSUE THREAD

**Issue by Handschrift** [aiko-chan-ai/DiscordBotClient#22]
Is it possible to provide a build for Linux (AppImage) in the releases-section, so Linux user don't have to build it from source?

Nevertheless, instructions for building it from source would be helpful as well.

**Comment by aiko-chan-ai** [comment]
building from source is very easy, you just need to install the dependency then use `npm run linux`
maybe I'll do a linux build (I don't have a VM installed at the moment)

**Comment by Handschrift** [comment]
I already compiled it from source successfully. Is there any way I can provide the build AppImage?

**Comment by aiko-chan-ai** [comment]
![image](https://user-images.githubusercontent.com/71698422/233354581-533e11ce-a4d4-45f0-9429-043357d2d507.png)
thank you, but maybe i'll do it myself
