### ISSUE TITLE
Notification hell

### ISSUE THREAD

**Issue by Pokegali** [aiko-chan-ai/DiscordBotClient#23]
When I log in with a bot token, I instantly get spammed with notifications coming from more than 200 servers and half of them have by default notifications for all messages.
And I manually set the notifications to mentions only.
I was wondering if there was an automated way of doing that or maybe it would be possible to save the settings?
Because after rebooting the client, the notification hell starts again.

**Comment by aiko-chan-ai** [comment]
Set status dnd

**Comment by aiko-chan-ai** [comment]
![image](https://user-images.githubusercontent.com/71698422/233902618-ff7ad30b-8b0f-478d-bce5-866e149273cb.png)

**Comment by Pokegali** [comment]
Oh, ok, yeah that works.
But is there any way to still receive some notifications after that?
For example, when the bot is pinged, or on a few servers where explicitly want to have all notifications.

**Comment by aiko-chan-ai** [comment]
I don't currently save your settings to a file, but maybe in the future

**Comment by Pokegali** [comment]
Ok ok. Maybe this could be great, because it always resets the settings. I'm guessing it's because discord doesn't allow bots to do that.
So if you could do that it would be a great addition I think, because you could also save opened dms maybe ?
But if you can't it's okay, it's not critical..
Also talking about dms, there's this weird bug where sometimes it shows the bot itself in the list instead of the other person. Maybe I should open another issue for that though.

**Comment by aiko-chan-ai** [comment]
> So if you could do that it would be a great addition I think, because you could also save opened dms maybe ?

very hard, this needs a database and I won't do it

> Also talking about dms, there's this weird bug where sometimes it shows the bot itself in the list instead of the other person.

I dont quite understand what you mean 💀

**Comment by Pokegali** [comment]
Ok, I understand x)

And well, this is what I mean :
![image](https://user-images.githubusercontent.com/83755025/234545568-1401925a-f00a-4af3-aab6-fc2ac2910147.png)
As you can see on the left there is twice the bot itself, but the dms are with other people (me and my alt)
It happens when the bot sends a dm by itself, it makes it appear like that in the list

**Comment by aiko-chan-ai** [comment]
Can you make a video on how to do that? i tried but no error

**Comment by Pokegali** [comment]
You just need to send a dm without using the client
[Capture vidéo du 2023-04-26 20-12-48.webm](https://user-images.githubusercontent.com/83755025/234666353-e6171970-0759-40ce-bb45-bedb1f4862fc.webm)

**Comment by aiko-chan-ai** [comment]
https://github.com/discord/discord-api-docs/blob/main/docs/Change_Log.md#api-and-gateway-v8
I'm handling this event (`CHANNEL_CREATE`) manually, which seems to be a problem. i will fix it soon

**Comment by aiko-chan-ai** [comment]
djs also got this error

**Comment by aiko-chan-ai** [comment]
@Pokegali fixed

**Comment by Pokegali** [comment]
Thanks ! x)
I tried it on my side and it worked
