### ISSUE TITLE
A bug maybe or my client is messed up

### ISSUE THREAD

**Issue by TejasLamba2006** [aiko-chan-ai/DiscordBotClient#25]
![image](https://user-images.githubusercontent.com/73745640/235172602-099eeb6b-9724-4788-82f9-2b366a3805a1.png)
I also tried reinstalling but this is what I get in my console and the screen is grey

**Comment by TejasLamba2006** [comment]
Tried messaging you on discord but ahh 
![image](https://user-images.githubusercontent.com/73745640/235173090-775397f7-e8f5-4e64-afe5-b00a2ef10e45.png)

**Comment by aiko-chan-ai** [comment]
> ![image](https://user-images.githubusercontent.com/73745640/235172602-099eeb6b-9724-4788-82f9-2b366a3805a1.png) I also tried reinstalling but this is what I get in my console and the screen is grey

![image](https://user-images.githubusercontent.com/71698422/235184731-c98d77e5-1b42-4807-9492-c3222148148f.png)

**Comment by TejasLamba2006** [comment]
I already tried that option I managed to fix it by clearing the Local Storage of electron and reinstalling the app

**Comment by aiko-chan-ai** [comment]
@TejasLamba2006 fixed

**Comment by TejasLamba2006** [comment]
Yes, you can close the issue
