### ISSUE TITLE
soft locked

### ISSUE THREAD

**Issue by spookmasterluke** [aiko-chan-ai/DiscordBotClient#27]
hello! i have been soft locked from accessing the app due to the vencord setting called "showhiddenchannels" it breaks the entire app.

**Comment by aiko-chan-ai** [comment]
soft locked ?

**Comment by spookmasterluke** [comment]
so when i use any plugin with vencord it entirely breaks the client and trying to re-open it only displays the servers youre in and you cant access settings, or anything else. although this may be my own issue,

**Comment by aiko-chan-ai** [comment]
can you make a video about it?

**Comment by aiko-chan-ai** [comment]
i also use `showhiddenchannels` plugin and it's very normal

**Comment by spookmasterluke** [comment]
ill see if i can

**Comment by spookmasterluke** [comment]
it might be a issue on my end but i have no idea, it just makes everything unaccessable ill do it rn since nobodies dming me

**Comment by aiko-chan-ai** [comment]
.-.

**Comment by spookmasterluke** [comment]
https://user-images.githubusercontent.com/111714642/235367976-47e3824b-9d5e-4ccb-9275-1f9afd760454.mp4

**Comment by aiko-chan-ai** [comment]
if you can't get into settings, run this command then restart the app
`Vencord.Settings.plugins.FakeNitro.enabled = false`
after going into settings disable the plugin `FakeNitro`

**Comment by aiko-chan-ai** [comment]
bot can't use features like screen sharing, so that's why it crashed

**Comment by spookmasterluke** [comment]
oh alright! so, fake nitro is the reason it messes up?

**Comment by spookmasterluke** [comment]
> bot can't use features like screen sharing, so that's why it crashed

ah i understand now

**Comment by aiko-chan-ai** [comment]
> oh alright! so, fake nitro is the reason it messes up?

yep

**Comment by spookmasterluke** [comment]
thank you!

> > oh alright! so, fake nitro is the reason it messes up?
> 
> yep
