### ISSUE TITLE
Settings -> Notifications

### ISSUE THREAD

**Issue by spookmasterluke** [aiko-chan-ai/DiscordBotClient#28]
I'm so sorry if the issue reports are stressing you out 😭😭so i apologize, but when you open notifications to change settings discord crashes. Thank you for everything!

**Comment by aiko-chan-ai** [comment]
sorry for your experience, i will release a hotfix soon

**Comment by spookmasterluke** [comment]
nooo i love the app and everything about it im just reporting the minor things that i encounter 😭😭 i really appreciate that youve made something so nice! and alright, again i really appreciate your effort towards this app and i love it! thank you 😊

**Comment by aiko-chan-ai** [comment]
v2.1.3 (Currently I can only build the version for windows & linux)

**Comment by spookmasterluke** [comment]
> v2.1.3 (Currently I can only build the version for windows)

thats all good! im on windows but sadly some people arent 😭

**Comment by aiko-chan-ai** [comment]
tomorrow there will be a version for macos.
you can close this if it works

**Comment by spookmasterluke** [comment]
> tomorrow there will be a version for macos. you can close this if it works

sick!!

also thank you!!! 😄
