### ISSUE TITLE
Soft Lock (2.1.3)

### ISSUE THREAD

**Issue by xNexusACS** [aiko-chan-ai/DiscordBotClient#29]
okay, so, somehow, im softlocked in the Main page, nothing works, and If I click something, the Vencord crash recovery says trying to recover but it does not do anything, some interfaces does not work, I enabled some vencord plugins so that can be the problem, the problem is, idk how to disable them since nothing works
![Capture](https://user-images.githubusercontent.com/83370388/236685425-11168ea3-2ca7-45ee-a89e-93f8835989bb.PNG)

**Comment by aiko-chan-ai** [comment]
![image](https://user-images.githubusercontent.com/71698422/236692716-e18fee27-e355-48af-8795-fcd1e6fdabd6.png)

**Comment by aiko-chan-ai** [comment]
let me know which plugin you have enabled

**Comment by aiko-chan-ai** [comment]
https://github.com/aiko-chan-ai/DiscordBotClient/issues/27#issuecomment-1529094919

**Comment by xNexusACS** [comment]
> let me know which plugin you have enabled

I don't fully know all of them, since I can't see which one I have enabled bcs I can't access the settings, some Plugin APIs probably

**Comment by shirouo** [comment]
> > let me know which plugin you have enabled
> 
> I don't fully know all of them, since I can't see which one I have enabled bcs I can't access the settings, some Plugin APIs probably

do you have fakenitro enabled? if you remember,

**Comment by xNexusACS** [comment]
I managed to restore the data, now its working properly
