### ISSUE TITLE
Embed

### ISSUE THREAD

**Issue by louanfontenele** [aiko-chan-ai/DiscordBotClient#3]
How can I use/create embeds?

**Comment by aiko-chan-ai** [comment]
> How can I use/create embeds?

This feature is currently not supported, I will add it in the future 

maybe https://github.com/aiko-chan-ai/BetterDiscord-Embeds

**Comment by louanfontenele** [comment]
Hope you add soon. Your software is amazing, thanks. Maybe I'll create a video talking about your program

**Comment by aiko-chan-ai** [comment]
> Hope you add soon. Your software is amazing, thanks. Maybe I'll create a video talking about your program

ty <3

**Comment by aiko-chan-ai** [comment]
@louanfontenele 
maybe i will create a function in console
Support embed, button and menu ?
![image](https://user-images.githubusercontent.com/71698422/205835338-e38db954-eacc-4cc4-b36a-b8e80eb9eeb5.png)

**Comment by louanfontenele** [comment]
> @louanfontenele maybe i will create a function in console Support embed, button and menu ? ![image](https://user-images.githubusercontent.com/71698422/205835338-e38db954-eacc-4cc4-b36a-b8e80eb9eeb5.png)

It will be perfect. If you can put a button to generate the embed will be better than perfect.

**Comment by aiko-chan-ai** [comment]
![image](https://user-images.githubusercontent.com/71698422/205927310-cac0a18f-847b-4923-bc7e-1f31cfcaf0e8.png)

I tried another way but no success .-.

**Comment by aiko-chan-ai** [comment]
removed these constructors in the latest version
xd

**Comment by aiko-chan-ai** [comment]
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/266a2b25-9cf0-4dcd-9f74-0c8616042308)
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/072b81be-29e1-4045-bb85-183774764ef1)
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/6d2adb85-c6b8-4757-b919-668015e8be58)
v2.3.0

**Comment by aiko-chan-ai** [comment]
@louanfontenele is it good?

**Comment by louanfontenele** [comment]
Yes, thank you so much.
