### ISSUE TITLE
This is worked

### ISSUE THREAD

**Issue by GP4300** [aiko-chan-ai/DiscordBotClient#35]
but i wanna know how to make Discord System Message , i know that it would be little hard

**Comment by player10783** [comment]
ok

**Comment by aiko-chan-ai** [comment]
you need to edit the code

**Comment by player10783** [comment]
> 你需要編輯代碼

i know

**Comment by GP4300** [comment]
in where ?

**Comment by aiko-chan-ai** [comment]
I will write a tutorial after I update the core (discord build)

**Comment by GP4300** [comment]
thanks ヾ(≧▽≦*)o

**Comment by aiko-chan-ai** [comment]
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/07afd1dd-5650-44bb-9a89-e453bfeb5518)

hmm .-.

**Comment by GP4300** [comment]
Hmmmm-.-

**Comment by GP4300** [comment]
How to learn programming languages and what should I learn first?

**Comment by aiko-chan-ai** [comment]
javascript

**Comment by GP4300** [comment]
> javascript

What it’s used for

**Comment by GP4300** [comment]
> javascript

Which language(s) u have learned

**Comment by GP4300** [comment]
> ![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/07afd1dd-5650-44bb-9a89-e453bfeb5518)
> 
> 
> 
> hmm .-.

Uhhhhhh.....sorry for spam (when I ask the question,I don't know need to download git and node lol ,that why we need to read readme.md)
This is a nice app 
Again sorry for spam.-.

**Comment by aiko-chan-ai** [comment]
:3
