### ISSUE TITLE
can the bot dm user if the user don't dm bot

### ISSUE THREAD

**Issue by GP4300** [aiko-chan-ai/DiscordBotClient#38]

**Comment by aiko-chan-ai** [comment]
try it and see

**Comment by GP4300** [comment]
> try it and see

Already try to use his/her id and  username#(number)

**Comment by GP4300** [comment]
> > try it and see
> 
> Already try to use his/her id and username#(number)

And not work lol

**Comment by GP4300** [comment]
> try it and see

Close the question
