### ISSUE TITLE
Online Users List

### ISSUE THREAD

**Issue by KingKrex69** [aiko-chan-ai/DiscordBotClient#4]
In the latest veriosn 1.0.4 it doesnt display the online players, the page is blank

**Comment by aiko-chan-ai** [comment]
I disabled it (crash https://github.com/aiko-chan-ai/DiscordBotClient/commit/582e37709e5fa7d483a7dbc5e263568cdc04ac5c)

**Comment by KingKrex69** [comment]
> I disabled it (crash [582e377](https://github.com/aiko-chan-ai/DiscordBotClient/commit/582e37709e5fa7d483a7dbc5e263568cdc04ac5c))

still doesnt work, you just added the line as a comment and now it doesnt load the member list

**Comment by NekoCyan** [comment]
> > I disabled it (crash [582e377](https://github.com/aiko-chan-ai/DiscordBotClient/commit/582e37709e5fa7d483a7dbc5e263568cdc04ac5c))
> 
> still doesnt work, you just added the line as a comment and now it doesnt load the member list

As Aiko said, they have tried to display member but it keep crashing and can't be fixed rn.
If u are smarter, try to fix it, ez right?

**Comment by KingKrex69** [comment]
> > > I disabled it (crash [582e377](https://github.com/aiko-chan-ai/DiscordBotClient/commit/582e37709e5fa7d483a7dbc5e263568cdc04ac5c))
> > 
> > 
> > still doesnt work, you just added the line as a comment and now it doesnt load the member list
> 
> As Aiko said, they have tried to display member but it keep crashing and can't be fixed rn. If u are smarter, try to fix it, ez right?

the request for getting the member list is just added as a comment in 1.0.4, ofc its not going to work

**Comment by NekoCyan** [comment]
> > > > I disabled it (crash [582e377](https://github.com/aiko-chan-ai/DiscordBotClient/commit/582e37709e5fa7d483a7dbc5e263568cdc04ac5c))
> > > 
> > > 
> > > still doesnt work, you just added the line as a comment and now it doesnt load the member list
> > 
> > 
> > As Aiko said, they have tried to display member but it keep crashing and can't be fixed rn. If u are smarter, try to fix it, ez right?
> 
> the request for getting the member list is just added as a comment in 1.0.4, ofc its not going to work

U can try remove that comment and run the Client, the source actually public so free feel to edit and try it.
