### ISSUE TITLE
Not a question.

### ISSUE THREAD

**Issue by GP4300** [aiko-chan-ai/DiscordBotClient#40]
Remind you guys,2FA in this discord bot client  is your bot token

**Comment by aiko-chan-ai** [comment]
wdym

**Comment by GP4300** [comment]
> wdym

Maybe wrong grammar

**Comment by GP4300** [comment]
> wdym

Ah I forgot something that is u  can type anything not just token

**Comment by GP4300** [comment]
Sorry for the spam
