### ISSUE TITLE
Error while using wine

### ISSUE THREAD

**Issue by asudouser** [aiko-chan-ai/DiscordBotClient#41]
I use ur client on linux manjaro by wine, 1st launch was be great, but with freezes. But after realoading, program gives this error:
![](https://github.com/aiko-chan-ai/DiscordBotClient/assets/117682185/867af80b-fce8-49d2-9440-bfe5ed19f432)

**Comment by aiko-chan-ai** [comment]
I will build the linux version later

**Comment by aiko-chan-ai** [comment]
2.2.1 (linux release)
