### ISSUE TITLE
For 500+ servers bot?

### ISSUE THREAD

**Issue by yeci226** [aiko-chan-ai/DiscordBotClient#48]
title

**Comment by aiko-chan-ai** [comment]
Try it and see

**Comment by aiko-chan-ai** [comment]
Tested 300 servers ok

**Comment by yeci226** [comment]
Yea I tried my bot on 700+ servers but it can't

**Comment by aiko-chan-ai** [comment]
Pls take screenshot in console log

**Comment by aiko-chan-ai** [comment]
Or video

**Comment by yeci226** [comment]
This or something 
https://media.discordapp.net/attachments/1057244827688910850/1123562513326411856/image.png?width=546&height=671
https://media.discordapp.net/attachments/1057244827688910850/1123562541394694197/image.png?width=491&height=670

**Comment by aiko-chan-ai** [comment]
Bruh

**Comment by yeci226** [comment]
> Bruh

what happened

**Comment by aiko-chan-ai** [comment]
Idk any more information with these 2 pictures

**Comment by yeci226** [comment]
> Idk any more information with these 2 pictures

what else i need provide?

**Comment by yeci226** [comment]
https://cdn.discordapp.com/attachments/1057244827688910850/1124347722682613952/2023-06-30_22-35-19.mp4

**Comment by aiko-chan-ai** [comment]
I'll fix it, but I don't have a pc right now

**Comment by yeci226** [comment]
> I'll fix it, but I don't have a pc right now

Oh ok

**Comment by aiko-chan-ai** [comment]
sorry for the late response
i'm fixing the code 💀

**Comment by aiko-chan-ai** [comment]
fixed (v2.4.0)
