### ISSUE TITLE
Suggestion: Add ability to change bot status

### ISSUE THREAD

**Issue by EthanWinters2885** [aiko-chan-ai/DiscordBotClient#49]
It would be cool if there was some sort of way to have the bot have a certain status, for example

Playing **<game>**

Whether its a slash command or smth else

**Comment by aiko-chan-ai** [comment]
Try custom status, i patched it

**Comment by EthanWinters2885** [comment]
huh? Is it a separate respository?

**Comment by aiko-chan-ai** [comment]
BotClient
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/f7c65a4c-fe32-4c0b-bb58-4f1c9252b1b4)
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/85581b9e-1eb4-4b5d-b92c-fc3a45e7ce46)

Other
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/6874c037-de65-42e3-a582-144e88f21c5e)
