### ISSUE TITLE
suggestion: more customisable embeds

### ISSUE THREAD

**Issue by sillysinuo** [aiko-chan-ai/DiscordBotClient#50]
It should be able to send embeds and customise things like description, url of title, timestamp, thumbail, main image, author, author url, and author icon.

**Comment by aiko-chan-ai** [comment]
`/discohook url`

**Comment by sillysinuo** [comment]
Yea that works, but it would be cooler to have those options inside of the /embed command

**Comment by aiko-chan-ai** [comment]
Copy carl bot 💀

**Comment by aiko-chan-ai** [comment]
> Yea that works, but it would be cooler to have those options inside of the /embed command

it will be very complicated

**Comment by aiko-chan-ai** [comment]
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/bf6f4f18-2a95-4e33-97b3-a99bf623971c)
