### ISSUE TITLE
Token switching

### ISSUE THREAD

**Issue by gsrte** [aiko-chan-ai/DiscordBotClient#51]
I dont know how to change the token

**Comment by aiko-chan-ai** [comment]
I will write a slash command for it

**Comment by gsrte** [comment]
Thank you, but actually i solved it by resetting my bot's token

**Comment by gsrte** [comment]
and thank you for your fast response

**Comment by aiko-chan-ai** [comment]
Logout > login

**Comment by aiko-chan-ai** [comment]
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/e4ad5a1e-3031-4b85-8b81-6795ee0c01e8)

**Comment by aiko-chan-ai** [comment]
v2.4.0
