### ISSUE TITLE
Error when renaming, changing permissions, and adding roles to users or bots

### ISSUE THREAD

**Issue by CE1CECL** [aiko-chan-ai/DiscordBotClient#52]
It seems like a discord API issue, the error code is `{"message": "The request body contains invalid JSON.", "code": 50109}` and might be your html, because you are mixing v10 and v9 apis, which you cannot do, however, api v6, on my client, works just fine. This issue was reported to me in my DM's when I used your client on my website for like a couple of days, it was reverted for this, though reverting clients can cause cache issues (https://github.com/ChrisEric1/ChrisEric1.GitHub.io/issues/18) for others who cannot figure out how to clear their browser cache.

**Comment by CE1CECL** [comment]
Also got DBC working on android!
![Screenshot_20230707-191915](https://github.com/aiko-chan-ai/DiscordBotClient/assets/52040854/af85e9c6-b181-41c9-9d2b-ae351ccf5152)
![Capture](https://github.com/aiko-chan-ai/DiscordBotClient/assets/52040854/e32d1f40-c7da-4d45-a2b0-5c3245453631)

**Comment by aiko-chan-ai** [comment]
Wait...:skull:

**Comment by aiko-chan-ai** [comment]
> Also got DBC working on android! ![Screenshot_20230707-191915](https://user-images.githubusercontent.com/52040854/251878271-af85e9c6-b181-41c9-9d2b-ae351ccf5152.png) ![Capture](https://user-images.githubusercontent.com/52040854/251878274-e32d1f40-c7da-4d45-a2b0-5c3245453631.JPG)

Nice :+1:

**Comment by aiko-chan-ai** [comment]
>  because you are mixing v10 and v9 api

it's really not that much different

**Comment by aiko-chan-ai** [comment]
@CE1CECL 

https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/8a7b66bd-9bbc-41aa-a80f-a1023ba50a9d

**Comment by CE1CECL** [comment]
> @CE1CECL
> 2023-07-10.18-14-49.mp4

Was that the new commit that fixed it, or was nothing done when recording? I can test it later myself when I have time.

**Comment by aiko-chan-ai** [comment]
> Was that the new commit that fixed it, or was nothing done when recording? I can test it later myself when I have time.

it's not a commit to fix, because idk what happened

**Comment by aiko-chan-ai** [comment]
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/c492924e-322c-4f00-92b0-4044456813cc)
error due to your api @CE1CECL 
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/255aa875-8a9a-46dd-b7e2-782cd9d7976f)

**Comment by CE1CECL** [comment]
> ![image](https://user-images.githubusercontent.com/71698422/252878890-c492924e-322c-4f00-92b0-4044456813cc.png) error due to your api @CE1CECL ![image](https://user-images.githubusercontent.com/71698422/252879059-255aa875-8a9a-46dd-b7e2-782cd9d7976f.png)

Ah ok, seems like CORSflare is worse than I thought, since I reverted the CORSflare thingy, that one person had their issue fixed. The code is quite a mess anyways, but Samual used something before though it doesn't work anymore, still AFAIK used workers.dev with a tk domain (even asked about it in a issue in that repo). Though IDK how changing the API endpoint makes the app work anymore? (since im on linux now lol).

Maybe its https://github.com/ChrisEric1/ChrisEric1.GitHub.io/blob/old/CORSflare.js#L198-L211 and I didn't catch it

**Comment by aiko-chan-ai** [comment]
:sob:

**Comment by CE1CECL** [comment]
> sob

Yeah sorry for the trouble though, really am :(

**Comment by CE1CECL** [comment]
Wonder if people would like it going through someone else's api, nowadays, but then again some people who cant just run a zip extension through their browser are just idk (though on rare cases, chromebooks, like really old ones, or managed ones cant download anything, so how will that work?)

**Comment by aiko-chan-ai** [comment]
if using proxy api, it's easy to get rate limit :/

**Comment by CE1CECL** [comment]
> if using proxy api, it's easy to get rate limit :/

That too is true but i used cloudflare because discord uses them too, so i would think workers.dev would pass my ip and all needed info over?

**Comment by aiko-chan-ai** [comment]
Maybe...
