### ISSUE TITLE
Sharding implementation

### ISSUE THREAD

**Issue by kimjunseong04** [aiko-chan-ai/DiscordBotClient#58]
An error occurs for bots that require shading.
Like that video, you fell into an infinite loop after a warning message occurred.
Is it a problem that can be solved?

https://github.com/aiko-chan-ai/DiscordBotClient/assets/70435510/b6eac6e5-3954-4e8d-b756-0f183a8076cc

**Comment by kimjunseong04** [comment]
It's good if it can be solved by personal wish :)

**Comment by aiko-chan-ai** [comment]
😭

**Comment by aiko-chan-ai** [comment]
How many guilds does your bot have?

**Comment by kimjunseong04** [comment]
> How many guilds does your bot have?

About 30000 servers are participating

**Comment by aiko-chan-ai** [comment]
I'm thinking 2 implementations:
- 1: each electron window is a shard, but there will be problems with RAM
- 2: use only one shard, but must use command to switch

:sob:

**Comment by kimjunseong04** [comment]
Switching each shard also seems like a good idea!

**Comment by kimjunseong04** [comment]
Showing many servers in one window can obviously cause performance problems.

**Comment by aiko-chan-ai** [comment]
> Showing many servers in one window can obviously cause performance problems.

<img src="https://cdn.discordapp.com/emojis/793845556119339018.gif?size=256&quality=lossless">

**Comment by kimjunseong04** [comment]
In conclusion, is this problem correctable?

**Comment by aiko-chan-ai** [comment]
> In conclusion, is this problem correctable?

maybe...

**Comment by kimjunseong04** [comment]
> > In conclusion, is this problem correctable?
> 
> maybe...

I will support you!!

**Comment by aiko-chan-ai** [comment]
it's done
I hope it works well

(200 guilds / 1 shard)

![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/4f98d775-5e99-4700-9906-c85c1f835760)
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/766c9104-6ca6-4b6c-a3d0-9c3c3a9b41f4)
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/3cf4e727-7890-45bd-9ffb-f6fadb8a6ded)

**Comment by aiko-chan-ai** [comment]
v2.4.1

**Comment by kimjunseong04** [comment]
It works fine!
It's very interesting Thank you!

**Comment by BachLe2000** [comment]
totally not a privacy issue :clueless:
