### ISSUE TITLE
Webhook Crash

### ISSUE THREAD

**Issue by KingKrex69** [aiko-chan-ai/DiscordBotClient#6]
- Crashes the app when i spawn a webhook | After reload, everything is working

- The webhook url clipboard is `https://127.0.0.1/d/api/webhooks` instead of `https://discord.com/api`

![y6_6O_xQYBbk6dvTEciOQA](https://user-images.githubusercontent.com/116029736/207968212-81c7856b-15ef-426d-9bfe-ca4cc694ab71.png)

**Comment by aiko-chan-ai** [comment]
> * Crashes the app when i spawn a webhook | After reload, everything is working

- [x] Fixed (v1.0.6)

> * The webhook url clipboard is `https://127.0.0.1/d/api/webhooks` instead of `https://discord.com/api`

- I won't fix it, because it's very difficult to interact with clipboard api
