### ISSUE TITLE
Do u have support server for this ?

### ISSUE THREAD

**Issue by GP4300** [aiko-chan-ai/DiscordBotClient#60]

**Comment by aiko-chan-ai** [comment]
uhm, maybe soon

**Comment by GP4300** [comment]
> uhm, maybe soon

Nice

**Comment by player10783** [comment]
> uhm, maybe soon

U know what is "X.com"?

**Comment by GP4300** [comment]
> uhm, maybe soon

If u create that u must send it to me plssss

**Comment by aiko-chan-ai** [comment]
> U know what is "X.com"?

twitter right?

**Comment by GP4300** [comment]
> > U know what is "X.com"?
> 
> 
> 
> twitter right?
> 
> 

Yea lol
A:I saw a funny post on X!
B: Wut?

**Comment by GP4300** [comment]
> uhm, maybe soon

Uhhh I forgot to read ur profile .w.

**Comment by player10783** [comment]
u don't accept my friend request lol
