### ISSUE TITLE
loading problem

### ISSUE THREAD

**Issue by xlHomingz** [aiko-chan-ai/DiscordBotClient#61]
when i launch it keeps loading but never loads. i tried reinstalling but it's the same problem
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/76704738/e78a5d8f-95cb-4fdf-be41-c359563f7d15)

**Comment by aiko-chan-ai** [comment]
Can i get debug log ?

**Comment by aiko-chan-ai** [comment]
F12 devtools

**Comment by xlHomingz** [comment]
where can i find debug log?

**Comment by xlHomingz** [comment]
oh i fixed it. thank you very much because you reminded me f12 thing
