### ISSUE TITLE
Label "Discord Team"

### ISSUE THREAD

**Issue by Iinksafe** [aiko-chan-ai/DiscordBotClient#65]
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/78565096/4158c229-483d-4a1e-aa88-43bc6c0d8136)
This is probably something that should be changed in the app itself (DiscordBotClient) because it's not really the Discord
Team, but aiko-chan-ai System account.

**Comment by aiko-chan-ai** [comment]
ehe

**Comment by aiko-chan-ai** [comment]
It's related to i18n so I won't edit it anymore

**Comment by Iinksafe** [comment]
Awesome, thanks for the update!
