### ISSUE TITLE
Loading

### ISSUE THREAD

**Issue by xlHomingz** [aiko-chan-ai/DiscordBotClient#67]
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/76704738/fb3ff5d6-b03a-4340-9f85-5df996955d6f)

it keeps loading and never launches

**Comment by aiko-chan-ai** [comment]
Log ;-;

**Comment by GP4300** [comment]
> Log ;-;

BTW
Where is logs...

**Comment by xlHomingz** [comment]
> > Log ;-;
> 
> BTW Where is logs...

how do i get the logs can you tell me exactly

**Comment by aiko-chan-ai** [comment]
ctrl + shift + i => ss

**Comment by GP4300** [comment]
> ctrl + shift + i => ss

Thx

**Comment by xlHomingz** [comment]
> ctrl + shift + i => ss

![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/76704738/0fe8068b-82b1-4afb-a6dd-278460bafef7)

**Comment by aiko-chan-ai** [comment]
...

**Comment by john-bv** [comment]
Having the same issue, seems to be this:

> ```sh
> Uncaught (in promise) Error: Cannot find module './notosans-400-normalitalic.woff2'
>     at 9a287279797be8995feb.js:7
>     at async Promise.all (index 3)
> ```
> 
> Worth noting, here are the other logs,
>  it's successfully dumping my application data in console as well.

**Comment by xlHomingz** [comment]
> Having the same issue, seems to be this:
> ```xl
> Uncaught (in promise) Error: Cannot find module './notosans-400-normalitalic.woff2'
>     at 9a287279797be8995feb.js:7
>     at async Promise.all (index 3)
> ```
> ![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/16673758/2aac65c6-8b43-41b9-9647-7af843f3030a)
> 
> Worth noting, here are the other logs,
> ![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/16673758/4f5d8b6a-2a4f-4ac7-afad-b49d9a30d77e)
> 
>  it's successfully dumping my application data in console as well.

i guess thats because of vencord because i uninstalled vencord and then bot client worked but when i reinstalled vencord bot client stopped again

**Comment by john-bv** [comment]
The fix here seems to be intents, @xlHomingz please make sure you have the following things enabled:
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/16673758/49d82a88-a463-4726-93fe-bdfe532db4b1)

**Comment by john-bv** [comment]
@aiko-chan-ai maybe we can add something on the login screen to make it more clear to enable these intents 😄 ?

**Comment by xlHomingz** [comment]
> The fix here seems to be intents, @xlHomingz please make sure you have the following things enabled:
> ![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/16673758/49d82a88-a463-4726-93fe-bdfe532db4b1)
> 

already enabled. check just now

**Comment by john-bv** [comment]
did you try relogging in?

**Comment by john-bv** [comment]
> ord because i uninstalled vencord and then bot client worked but when i reinstalle

this is an interesting issue, i'll try to reprod..., maybe try clearing the app cache and reinstalling.

**Comment by xlHomingz** [comment]
i fully uninstalled bot client from program files and reinstalled for
multiple times it doesn't work. i guess i should remove vencord since it's
the main barrier

**Comment by john-bv** [comment]
did you remove the program cache in app-data as well? I suspect its an issue with that.

**Comment by xlHomingz** [comment]
it don't think so

**Comment by aiko-chan-ai** [comment]
https://cdn.discordapp.com/attachments/1145118731857571861/1145205254590304356/2023-08-27_10-52-54.mp4

**Comment by xlHomingz** [comment]
wait. should i enable those or disable?

**Comment by aiko-chan-ai** [comment]
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/708eb98f-4435-4c6c-94e1-078e89543d13)
