### ISSUE TITLE
Discord added the ability for bots to have custom statuses without "Playing" "Watching" etc

### ISSUE THREAD

**Issue by EthanWinters2885** [aiko-chan-ai/DiscordBotClient#68]
What if you updated the status thingy where it displays whatever you type without the "Playing" since Discord added it recently 

Proof:
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/90074580/05024eea-3ead-451c-9489-fd283373abfc)
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/90074580/17c2fc8d-e043-415f-a989-bd4a8d116250)

**Comment by aiko-chan-ai** [comment]
https://github.com/aiko-chan-ai/DiscordBotClient/commit/73a39ea0e8c1d4422722221e1b8cb0b522ea2e55
