### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by PixelatedPurple** [aiko-chan-ai/DiscordBotClient#69]
The client never loads [](url)
![Discord Bot Client 9_1_2023 9_41_16 PM](https://github.com/aiko-chan-ai/DiscordBotClient/assets/85250250/ac543527-41ff-4e26-86a7-a605fb3e7b2b)

**Comment by aiko-chan-ai** [comment]
This is not my client

**Comment by PixelatedPurple** [comment]
I saw what i did wrong i still had the flam3rboy client installed thats why my bad
