### ISSUE TITLE
Cannot use commands

### ISSUE THREAD

**Issue by hakergeniusz** [aiko-chan-ai/DiscordBotClient#70]
I can't use any commands other than the default ones from discord even though the bot has permission to do so

**Comment by aiko-chan-ai** [comment]
?

**Comment by hakergeniusz** [comment]
I cannot use any commands other than those built into Discord as a bot, even if I have permission

**Comment by aiko-chan-ai** [comment]
Can you give an example?

**Comment by hakergeniusz** [comment]
This is the case with all commands that come from bots (not those built into discord), and I checked whether it works on a normal user account and it worked normally

**Comment by aiko-chan-ai** [comment]
Your bot cannot use other bots' commands ;-;

**Comment by hakergeniusz** [comment]
ok

**Comment by hakergeniusz** [comment]
I did not know that
