### ISSUE TITLE
Unauthorized 

### ISSUE THREAD

**Issue by nimash3eshan** [aiko-chan-ai/DiscordBotClient#71]
After entering the bot token it keeps saying "Unauthorized".  What does that mean?

**Comment by nimash3eshan** [comment]
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/81243419/c2dc82bb-afdb-48ff-8476-65942ce281fd)

**Comment by GP4300** [comment]
Maybe try this 
> https://github.com/aiko-chan-ai/DiscordBotClient/issues/67#issuecomment-1694563033
