### ISSUE TITLE
logging out goes to default email:password login screen

### ISSUE THREAD

**Issue by xNasuni** [aiko-chan-ai/DiscordBotClient#72]
i don't know if it's just me but when i'm inside of a bot and i try logging out or adding another account it takes me to the login screen for normal accounts instead of the custom one that was made for bot logins
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/62818119/3ecdc541-c978-443a-bb66-9866a231c2bc)

**Comment by aiko-chan-ai** [comment]
try ctrl + R

**Comment by xNasuni** [comment]
that's what i do every time i go to that screen but it would be easier if it went back to that screen, i'll try making a PR to see if i can fix that.
