### ISSUE TITLE
Unable to expunge faulty token

### ISSUE THREAD

**Issue by SZBall** [aiko-chan-ai/DiscordBotClient#73]
When a friend of mine tried to get into the bot client but he forgot to turn on intents for the bot he wanted to use it with so he wasn't able to get in, however somehow he managed to lose access to the temporary account he wanted to have the bot on so it became impossible to turn intents on. He got things sorted on a different account but he saw that the client was still stuck trying to get the old token to work. After this, he tried searching for an in-program option to expunge the faulty token of which he found none, followed by uninstalling and reinstalling the program to no avail. Is there a way to expunge the faulty token or should I just tell him to try downloading a different client at this point?

**Comment by aiko-chan-ai** [comment]
try delete `C:\Users\<username>\AppData\Roaming\Discord Bot Client`

**Comment by SZBall** [comment]
It worked, thanks for the assistance.
