### ISSUE TITLE
Add support for more than 100 servers

### ISSUE THREAD

**Issue by RobbyV2** [aiko-chan-ai/DiscordBotClient#76]
Verified bots with proper intents can't access all of the servers due to the actual discord client blocking the user from viewing them all. Other issues mention that this is fixed, but as of version 2.4.1, for me I can't access more servers than the client allows for?

**Comment by aiko-chan-ai** [comment]
I tried with a bot with 600 servers, it's still normal (but I have shard support for bots with more than 2000 servers, see [here](https://github.com/aiko-chan-ai/DiscordBotClient/issues/58))

**Comment by RobbyV2** [comment]
Yup, that works thank you!
