### ISSUE TITLE
Fix the Bot client 

### ISSUE THREAD

**Issue by ghost** [aiko-chan-ai/DiscordBotClient#78]
Fix the Bot Client since for some reason, I check the console and it says "Cannot find module" and doesn't even load the actual client now.

**Comment by aiko-chan-ai** [comment]
I need screenshots

**Comment by aiko-chan-ai** [comment]
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/ecb1b970-7c76-4253-a16c-6d8ddcc208ad)

**Comment by ghost** [comment]
> ![image](https://user-images.githubusercontent.com/71698422/282475801-ecb1b970-7c76-4253-a16c-6d8ddcc208ad.png)

Hi again, here are some screenshots of what the console is saying:
![Screenshot_119](https://github.com/aiko-chan-ai/DiscordBotClient/assets/144738428/a4e2b7ec-6456-43cf-b3b5-3dff3b0286ca)
![Screenshot_118](https://github.com/aiko-chan-ai/DiscordBotClient/assets/144738428/df4af3b8-3ff1-4ea1-8dbb-efbcf1a10964)

**Comment by aiko-chan-ai** [comment]
hmm, can you tell me some information about your bot?
For example, the number of guilds that added bots, privilege intents...

**Comment by aiko-chan-ai** [comment]
I don't see any errors in the console

**Comment by ghost** [comment]
> I don't see any errors in the console
I don't know why it isn't loading at all then...

**Comment by aiko-chan-ai** [comment]
Have you tried reinstalling the application yet?

**Comment by ghost** [comment]
Yes, I have tried doing that... clicking on the exe file in my downloads folder so it replaces the files I guess

**Comment by ghost** [comment]
nvm, I just fixed it... I didn't reinstall, I just reset a bot token that I logged in from a bot, for some reason it was a bot token that was making it not load at all... 

also could you update the client since Discord broke vencord lately

**Comment by aiko-chan-ai** [comment]
You should manually delete the app's data
`C:\Users\<username>\AppData\Roaming\Discord Bot Client`

**Comment by aiko-chan-ai** [comment]
oh

**Comment by aiko-chan-ai** [comment]
> also could you update the client since Discord broke vencord lately

currently my app is not affected by discord (it's like an old clone)
I will update soon (currently I am preparing for the exam)

**Comment by ghost** [comment]
> currently my app is not affected by discord (it's like an old clone) I will update soon (currently I am preparing for the exam)

Oh, well good luck with your exams... But I'm sure you will pass easily

**Comment by aiko-chan-ai** [comment]
ty <3
