### ISSUE TITLE
Portable Version?

### ISSUE THREAD

**Issue by Wilk-22** [aiko-chan-ai/DiscordBotClient#80]
Is portable version possible?

**Comment by aiko-chan-ai** [comment]
Yes

**Comment by TechClusterHQ** [comment]
@aiko-chan-ai How is this possible exactly?

**Comment by Wilk-22** [comment]
@TechClusterHQ I used https://github.com/ChrisEric1/ChrisEric1.GitHub.io as its preaty much portable version of this. Hope you'll find this helpful
