### ISSUE TITLE
Unable To Open app 

### ISSUE THREAD

**Issue by djontop** [aiko-chan-ai/DiscordBotClient#81]
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/107875648/a46176d4-3e07-480e-84a0-3f4e6d158b0b)

**Comment by aiko-chan-ai** [comment]
"Please try again"
Reinstall app pls

**Comment by djontop** [comment]
> "Please try again" Reinstall app pls

Already Tried Not Working

**Comment by aiko-chan-ai** [comment]
try build from source
