### ISSUE TITLE
How to update to the new discord version (I've already read the readme 100times!)

### ISSUE THREAD

**Issue by Unrectified** [aiko-chan-ai/DiscordBotClient#82]
Hey, I'd like to update it to the newer discord version, but even after reading the readme several times, I can't get how to do that. Where are the files to updates, and how to get the update index.htlm?

## How to update to the latest Discord version ?

- Step 1: Patch index.html (Get it from discord.com/channels/@me)

- Step 2: Patch script.js (search for keyword `_doIdentify` in the code)

- Step 3: Change like me (see location in template file, search by keyword `// Patch #{number}`)

**Comment by VillainsRule** [comment]
The update instructions are for developers. Learn code, and read it again.
The index.html copy you should patch can be found at `view-source:https://discord.com/channels/@me`

**Comment by aiko-chan-ai** [comment]
In v3, I try not to interfere with the original script, so I can use the BotClient plugin (Vencord src) to patch (it will be easier to use).
