### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Justman100** [aiko-chan-ai/DiscordBotClient#87]
Got this:

> TypeError: Cannot read properties of undefined (reading 'commandLine')

**Comment by Justman100** [comment]
@aiko-chan-ai

**Comment by aiko-chan-ai** [comment]
I need screenshots

**Comment by Justman100** [comment]
> I need screenshots

![grafik](https://github.com/aiko-chan-ai/DiscordBotClient/assets/149507651/b2b72ca7-436b-4db2-a797-b2efaad090cc)

**Comment by aiko-chan-ai** [comment]
`electron .`

**Comment by aiko-chan-ai** [comment]
not `node .`

**Comment by Justman100** [comment]
> not `node .`

That in a permanent loop:
![grafik](https://github.com/aiko-chan-ai/DiscordBotClient/assets/149507651/f2d47219-b53a-4b73-9045-629a64eb4a5a)

**Comment by Justman100** [comment]
@aiko-chan-ai

Working! 🙂🥳

**Comment by Justman100** [comment]
Although it does like to get hung up! This do not change:
![grafik](https://github.com/aiko-chan-ai/DiscordBotClient/assets/149507651/61169ba3-4dae-425c-8c6e-f8d33ede1890)

**Comment by Justman100** [comment]
@aiko-chan-ai

**Comment by aiko-chan-ai** [comment]
Please clear app data and try again (I'm also updating to a new version ;-;)
