### ISSUE TITLE
Only allows me to see a max of 100 servers

### ISSUE THREAD

**Issue by Pikachubolk** [aiko-chan-ai/DiscordBotClient#89]

**Comment by aiko-chan-ai** [comment]
#58

**Comment by Pikachubolk** [comment]
but this only works if your shard has at least 100 servers if the bot has 1k servers per shard it excludes most

**Comment by aiko-chan-ai** [comment]
I had to limit the server load to avoid causing your pc to explode due to ram overflow (and per shard, I just set a limit of less than 200 guilds)

**Comment by Pikachubolk** [comment]
If that's that case how would you view the other servers, which are on that shard?

**Comment by aiko-chan-ai** [comment]
Just change shardid
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/428856a9-b4f1-4b1d-8d66-4a30c3552abb)

**Comment by Pikachubolk** [comment]
I though the shards we're the shards of my discord bot...

**Comment by aiko-chan-ai** [comment]
bc i divide each shard to have a maximum of 200 servers, the number of shards may be more than you think

**Comment by Pikachubolk** [comment]
also maybe a suggestion, but if you send for example a discord.gg invite link to the DM's of the bot you could maybe make it so if the bot is in that server that the bot will auto switch to the shard with that server and open the server, dunno if this is too much work, even tho I'm a js developer...

**Comment by aiko-chan-ai** [comment]
Complicated but I'll look into it

**Comment by aiko-chan-ai** [comment]
> also maybe a suggestion, but if you send for example a discord.gg invite link to the DM's of the bot you could maybe make it so if the bot is in that server that the bot will auto switch to the shard with that server and open the server, dunno if this is too much work, even tho I'm a js developer...


https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/e6dc66a6-08be-4ced-9136-6e7af4e30dd7

**Comment by aiko-chan-ai** [comment]
will be available in v3.2.1

**Comment by Pikachubolk** [comment]
Das cool 👍

**Comment by aiko-chan-ai** [comment]
you can build from source
