### ISSUE TITLE
Issue with "Vencord.Webpack.Common.Toasts"

### ISSUE THREAD

**Issue by moxie-coder** [aiko-chan-ai/DiscordBotClient#90]
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/124418090/667b2cbf-1695-480d-98a4-8bf4c4e175af)

This shows up after logging in, intents are enabled on the bot I was logging into, at first it gave me an issue similar to #87 but after reloading, now an new issue comes up (shown in screenshot above)

**Comment by aiko-chan-ai** [comment]
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/4676cf3c-0b1a-443b-9c17-2502e0fa51f7)
try clearing app data (I can't reproduce this error)

**Comment by moxie-coder** [comment]
k, I'll try

**Comment by moxie-coder** [comment]
worked
