### ISSUE TITLE
Keep discord status when app restarts

### ISSUE THREAD

**Issue by JavaProgswing** [aiko-chan-ai/DiscordBotClient#92]
The app switches back to online status whenever it starts, I want it to persist the status which was set previously.

**Comment by aiko-chan-ai** [comment]
very difficult bc bot doesn't save settings

**Comment by JavaProgswing** [comment]
no local configs?

**Comment by aiko-chan-ai** [comment]
try latest

**Comment by JavaProgswing** [comment]
Tried it on the latest version. When I set to invis and restart the app, it shows up in the app as offline but shows online to others.
@aiko-chan-ai

**Comment by JavaProgswing** [comment]
That should be opened as a new bug, but I am continuing that discussion here.

**Comment by wouwouz** [comment]
ive the same problem

**Comment by JavaProgswing** [comment]
@aiko-chan-ai Any ETA on this one?
