### ISSUE TITLE
Less noisy notifications

### ISSUE THREAD

**Issue by sitiom** [aiko-chan-ai/DiscordBotClient#94]
It would be nice to make the notifications less noisy. For example:

**Only notify when there is a new update**
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/56180050/28efc3f8-bef1-4e59-856d-cb2bd99cd72e)

**Option to turn this off**
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/56180050/114b5cdc-da41-4967-9345-685b4d33dd44)
It becomes very annoying every time you close the application to the tray
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/56180050/f55ce439-b690-4ec6-a904-38a0685fc89a)

**Comment by aiko-chan-ai** [comment]
;-;

**Comment by aiko-chan-ai** [comment]
try latest
