### ISSUE TITLE
Alt+F4 should minimize the client to tray instead of quitting app

### ISSUE THREAD

**Issue by sitiom** [aiko-chan-ai/DiscordBotClient#95]
I commonly use the Alt+F4 hotkey to close windows. However, DiscordBotClient quits when closed via the shortcut/hotkey, unlike the expected behavior of Discord and other apps, which minimize to tray. Please fix, thanks!

**Comment by aiko-chan-ai** [comment]
![image](https://github.com/aiko-chan-ai/DiscordBotClient/assets/71698422/ff2e8388-078b-4b84-a745-7314c8eb33cb)
Can you wait for v3?

**Comment by sitiom** [comment]
> Can you wait for v3?

Yes, I'm not in a rush 🙂

**Comment by aiko-chan-ai** [comment]
try latest

**Comment by sitiom** [comment]
Thanks! It works now
