### ISSUE TITLE
idk why but i stuck at loading page after i update it

### ISSUE THREAD

**Issue by GP4300** [aiko-chan-ai/DiscordBotClient#97]
where is the discord bot client file? i wanna deleted them and redownload

**Comment by aiko-chan-ai** [comment]
try latest

**Comment by GP4300** [comment]
> try latest
![螢幕擷取畫面 2024-02-04 213241](https://github.com/aiko-chan-ai/DiscordBotClient/assets/90902717/77fde028-78be-4b26-a148-0434b61c570b)
