### ISSUE TITLE
Cannot access any files of discord server / the app doesnt try to open

### ISSUE THREAD

**Issue by Aeyanhehe** [aiko-chan-ai/DiscordBotClient#99]
![image_2024-02-04_163857375](https://github.com/aiko-chan-ai/DiscordBotClient/assets/111239541/27f308b4-0c5d-4486-84f6-d4cf4652706f)
Here you go.

**Comment by aiko-chan-ai** [comment]
What version is this?

**Comment by Aeyanhehe** [comment]
> What version is this?

the latest which you uploaded like 30 mins ago

**Comment by aiko-chan-ai** [comment]
oh

**Comment by aiko-chan-ai** [comment]
try latest
